In [3]:
!pip install torch

In [4]:
import torch

In [5]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones([3, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [8]:
x = torch.Tensor([[1., 2., 3., 4.],
                  [5., 6., 7., 8.],
                  [9., 10., 11., 12.]])

In [10]:
x.size()

torch.Size([3, 4])

In [11]:
x.shape

torch.Size([3, 4])

In [12]:
x[0]

tensor([1., 2., 3., 4.])

In [13]:
x[0, 0]

tensor(1.)

In [14]:
x[:, 0]

tensor([1., 5., 9.])

In [15]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [17]:
x ** 2

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [18]:
y = torch.Tensor([[1., 2., 3., 4.],
                  [5., 6., 7., 8.],
                  [9., 10., 11., 12.]])

In [19]:
x + y

tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])

In [20]:
x * y

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [21]:
x / y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
x % y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [24]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [25]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

<p>Реализуйте при помощи pyTorch функцию, которая возвращает <strong>сумму (x.sum())</strong> элементов тензора X, строго превышающих значение <code>limit</code>, которое является входным значением алгоритма.</p>
<p>Входная матрица: <code>X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])</code></p>

In [26]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = (X[X > limit]).sum()

print(larger_than_limit_sum)

1
tensor(44)


In [27]:
y = x
y[0, 0] = 999
print(x)
print(y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [30]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x
y[2] = torch.ones(3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1]])

In [31]:
x = torch.Tensor([[1., 2., 3., 4.],
                  [5., 6., 7., 8.],
                  [9., 10., 11., 12.]])
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [32]:
x.dtype

torch.float32

In [33]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [34]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [35]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=torch.int32)

In [37]:
x = torch.rand([10,10])
x

tensor([[1.2775e-01, 7.8519e-01, 4.1294e-01, 6.2987e-01, 1.7056e-01, 1.1149e-01,
         3.1550e-01, 1.0940e-01, 1.7650e-01, 9.3626e-01],
        [6.2121e-01, 9.6407e-01, 5.0525e-01, 7.8221e-01, 9.4212e-01, 4.8091e-01,
         7.1508e-01, 7.5842e-01, 1.7688e-01, 1.1312e-01],
        [3.2141e-01, 7.7052e-01, 7.7085e-01, 8.6106e-01, 8.9263e-01, 2.0300e-02,
         5.0952e-01, 2.6306e-02, 9.2918e-01, 4.2785e-01],
        [4.1449e-01, 8.5712e-01, 6.5352e-01, 2.8524e-01, 8.6175e-01, 4.1144e-02,
         3.2487e-01, 7.5916e-01, 9.0532e-01, 6.0876e-01],
        [1.6042e-02, 1.8895e-01, 7.5965e-01, 3.8714e-01, 8.9453e-01, 4.9271e-01,
         7.5950e-01, 4.0691e-03, 5.1670e-01, 7.4751e-01],
        [3.6265e-01, 6.2861e-01, 6.8764e-01, 2.4363e-02, 8.7114e-02, 1.5716e-01,
         2.6041e-04, 6.7751e-01, 1.9028e-02, 4.5858e-01],
        [8.4339e-01, 9.8296e-01, 4.5837e-02, 4.6416e-01, 1.8456e-01, 8.5899e-01,
         1.9806e-01, 8.4468e-01, 9.2741e-01, 8.4673e-01],
        [8.6720e-02, 9.5047

In [38]:
torch.cuda.is_available()

True

In [39]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [40]:
torch.device('cpu')

device(type='cpu')

In [41]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [47]:
x = torch.rand([2000,3000])

In [48]:
x_cuda = x.to(device)

In [49]:
%time y = (x - x + x * 10.0) ** 2

Wall time: 23 ms


In [50]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

Wall time: 1.01 ms


Прирост в 23 раза (!!)